name: cd

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest
    environment: Production

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - id: "auth"
        uses: "google-github-actions/auth@v0"
        with:
          credentials_json: "${{ secrets.GCP_SA_KEY }}"

      # Setup gcloud CLI
      - uses: google-github-actions/setup-gcloud@v0

      # Build docker image
      - name: Build Docker Image
        run: |-
          docker build -t us.gcr.io/${{ secrets.PROJECT_ID }}/${{ secrets.SERVICE_NAME }}:${{ github.sha }} .
      # Configure docker to use the gcloud command-line tool as a credential helper
      - run: |
          gcloud auth configure-docker -q
      # Push image to Google Container Registry
      - name: Push Docker Image to GCR
        run: |-
          docker push us.gcr.io/${{ secrets.PROJECT_ID }}/${{ secrets.SERVICE_NAME }}:${{ github.sha }}

  deploy:
    name: Deploy Image to Cloud Run
    runs-on: ${{ matrix.os }}
    needs: build
    environment: Production

    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - id: "auth"
        uses: "google-github-actions/auth@v0"
        with:
          credentials_json: "${{ secrets.GCP_SA_KEY }}"

      # extract branch name
      - name: Extract branch name
        shell: bash
        run: echo "BRANCH_NAME=$(echo ${GITHUB_REF##*/})" >> $GITHUB_ENV

      - name: Deploy to Cloud Run
        uses: "google-github-actions/deploy-cloudrun@main"
        with:
          image: us.gcr.io/${{ secrets.PROJECT_ID }}/${{ secrets.SERVICE_NAME }}:${{ github.sha }}
          service: ${{ secrets.SERVICE_NAME }}-${{ env.BRANCH_NAME }}
          region: ${{ secrets.SERVICE_REGION }}
          env_vars: |
            NODE_ENV=${{ env.NODE_ENV }},
            NUXT_ENV_API_HOST="${{ secrets.NUXT_ENV_API_HOST }}",
            NUXT_ENV_API_HOST_WS="${{ secrets.NUXT_ENV_API_HOST_WS }}",
            NUXT_ENV_OFFICE_EMAIL="${{ secrets.NUXT_ENV_OFFICE_EMAIL }}",
            NUXT_ENV_LOGO_BASE64="${{ secrets.NUXT_ENV_LOGO_BASE64 }}",
            NUXT_ENV_RAZON_SOCIAL="${{ secrets.NUXT_ENV_RAZON_SOCIAL }}",
            NUXT_ENV_GIRO="${{ secrets.NUXT_ENV_GIRO }}",
            NUXT_ENV_DIRECCION="${{ secrets.NUXT_ENV_DIRECCION }}",
            NUXT_ENV_RUT="${{ secrets.NUXT_ENV_RUT }}",
            NUXT_ENV_FONO="${{ secrets.NUXT_ENV_FONO }}",
            NUXT_ENV_CONTACTO_EMAIL="${{ secrets.NUXT_ENV_CONTACTO_EMAIL }}"
